apiVersion: v1
kind: Service
metadata:
  name: hello-vois-svc
  labels:
    app: hello-vois-svc
spec:
  selector:
    app: hello-vois
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

